using System.ComponentModel.DataAnnotations;

namespace Projekt001.Entities
{
    public class ContactEntity
    {
        [Key] // Primary Key
        public int ContactId { get; set; }

        [Required]
        [StringLength(100)]
        public string? Name { get; set; }

        [Required]
        [StringLength(100)]
        public string? Email { get; set; }

        [Required]
        [StringLength(2000)]
        public string? Message { get; set; }

        public DateTime SendDate { get; set; }

        public static ContactEntity FromModel(Models.ContactModel model)
        {
            return new ContactEntity
            {
                // ContactId is auto-generated by the database
                Name = model.Name,
                Email = model.Email,
                Message = model.Message,
                SendDate = DateTime.UtcNow // Use UtcNow for consistency across time zones
            };
        }
    }
}